setono_sylius_wishlist_shop_wishlist_index:
    methods: [GET]
    path: /wishlists
    controller: Setono\SyliusWishlistPlugin\Controller\WishlistIndexAction
    
setono_sylius_wishlist_shop_wishlist_show:
    methods: [GET,PATCH]
    path: /wishlists/{uuid}
    controller: Setono\SyliusWishlistPlugin\Controller\ShowWishlistAction

setono_sylius_wishlist_shop_wishlist_add_product:
    methods: [GET]
    path: /wishlist/add-product/{id}
    controller: setono_sylius_wishlist.controller.add_product_to_wishlist
    requirements:
        id: '\d+'
        
setono_sylius_wishlist_shop_wishlist_add_product_variant:
    methods: [GET]
    path: /wishlist/add-product/{id}
    controller: setono_sylius_wishlist.controller.add_product_variant_to_wishlist
    requirements:
        id: '\d+'
        
setono_sylius_wishlist_shop_wishlist_remove_product:
    methods: [GET]
    path: /wishlist/remove-product/{id}/{wishlist}
    controller: setono_sylius_wishlist.controller.remove_product_from_wishlist
    defaults:
        wishlist: null
    requirements:
        id: '\d+'
        wishlist: '\d+'
        
setono_sylius_wishlist_shop_wishlist_remove_product_variant:
    methods: [GET]
    path: /wishlist/remove-product-variant/{id}
    controller: setono_sylius_wishlist.controller.remove_product_variant_from_wishlist
    requirements:
        id: '\d+'

setono_sylius_wishlist_shop_wishlist_select_wishlists:
    methods: [POST]
    path: /wishlist/select-wishlists/{product}
    controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::selectWishlists
    requirements:
        product: '\d+'
        
setono_sylius_wishlist_shop_wishlist_add_to_cart:
    methods: [GET]
    path: /wishlists/{uuid}/add-to-cart
    controller: Setono\SyliusWishlistPlugin\Controller\AddWishlistToCartAction
