setono_sylius_wishlist_shop_wishlist_add:
    methods: [POST,GET]
    path: /wishlist/add/{product}
    controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::add
    requirements:
        product: '\d+'
        
setono_sylius_wishlist_shop_wishlist_select_wishlists:
    methods: [POST]
    path: /wishlist/select-wishlists/{product}
    controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::selectWishlists
    requirements:
        product: '\d+'
