setono_sylius_wishlist_shop_wishlist_add:
    methods: [POST,GET]
    path: /wishlist/add/{product}
    controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::add
    requirements:
        product: '\d+'
        
setono_sylius_wishlist_shop_wishlist_update_product_wishlists:
    methods: [POST]
    path: /wishlist/product-wishlists/{product}
    controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::updateProductWishlists
    requirements:
        product: '\d+'
