setono_sylius_wishlist_shop_wishlist_add:
    path: /wishlist/add/{productVariant}
    methods: [POST]
    defaults:
        controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::add
