setono_sylius_wishlist_plugin_shop_wishlist_add:
    path: /wishlist/add/{productVariant}
    methods: [POST]
    _defaults:
        controller: Setono\SyliusWishlistPlugin\Controller\WishlistController::add
